[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chess_features"
version = "0.0.1"
authors = [
  { name="Joel Ewig", email="joel.ewig@gmail.com" },
]
description = "Package for transforming a chess board into different representations usable in Machine Learning"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
